version: "2"
services:
  webapp:
    build: ./
    image: amitsaha/flask_app:demo1
    container_name: webapp 
    expose:
      - 5000
    volumes:
      - ./src:/application
  client:
    depends_on:
      - webapp
    build:
      context: ./
      dockerfile: Dockerfile-client
    image: amitsaha/flask_app:client
    container_name: client
  analyzer:
    depends_on:
      - client
    expose:
      - 8888
    ports:
      - 8888:8888
    image: jupyter/datascience-notebook
    container_name: analyser
    volumes:
      - ./src:/data/
